version: '3'

services:
  app:
    build: .
    entrypoint: sh -c "npm install && npm run start"
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    networks:
      - default
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - db_persdata:/var/lib/postgrespers
    networks:
      - default
networks:
  default:
volumes:
  db_persdata : {}